version: 2

project_name: kiosk

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/reflective-technologies/kiosk-cli/cmd.Version={{.Version}}
      - -X github.com/reflective-technologies/kiosk-cli/cmd.GitHubClientID={{ .Env.GITHUB_OAUTH_CLIENT_ID }}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: reflective-technologies
    name: kiosk-cli
  draft: false
  prerelease: auto
